# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Active MC version for manifold
#active_mc_version=26.1
#active_mc_version=1.21.11
#active_mc_version=1.21.8
#active_mc_version=1.21.4
#active_mc_version=1.21.1
#active_mc_version=1.20.6
#active_mc_version=1.20.4
active_mc_version=1.20.1

# Project Properties
mod_version=0.12.0-beta
maven_group=io.github.mikip98.humilityafm
archives_base_name=humility-afm

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.19.1
loom_version=1.16-SNAPSHOT

# Global Dependencies
lombok_plugin_version=9.2.0
manifold_plugin_version=0.0.2-alpha
manifold_version=2026.1.6
