# Environment Requirements
minecraft_version=1.20.1
mc_version_number=12001
java_version=17

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.20.1+build.10
fabric_version=0.92.7+1.20.1

# Other Dependencies
config2_version=11.1.136
modmenu_version=7.2.2

# Polymorph runtime
polymorph_version=0.49.10+1.20.1
polymorph_cca_version=5.2.3

