# Environment Requirements
minecraft_version=1.21.4
mc_version_number=12104
java_version=21

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=61
resource_pack_format=46

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.4+build.8
fabric_version=0.119.4+1.21.4

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=17.0.144
modmenu_version=13.0.3
polymer_version=0.11.8+1.21.4
