# Environment Requirements
minecraft_version=1.21.1
mc_version_number=12101
java_version=21

# Pack Formats
resource_pack_format=34
data_pack_format=48

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.1+build.3
fabric_version=0.116.9+1.21.1

# Other Dependencies
config2_version=15.0.140
modmenu_version=11.0.3

# Polymorph runtime
polymorph_version=1.1.0+1.21.1
polymorph_cca_version=6.1.0
