# Environment Requirements
minecraft_version=1.21.11
mc_version_number=12111
java_version=21

# Pack Formats
data_pack_format=94
resource_pack_format=75

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.11+build.4
fabric_version=0.141.3+1.21.11

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=21.11.153
modmenu_version=17.0.0-beta.2
