# Environment Requirements
minecraft_version=1.21.8
mc_version_number=12108
java_version=21

# Pack Formats
data_pack_format=81
resource_pack_format=64

# Fabric Properties
# check these on https://fabricmc.net/develop
yarn_mappings=1.21.8+build.1
fabric_version=0.136.1+1.21.8

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=19.0.147
modmenu_version=15.0.1
