# Environment Requirements
minecraft_version=26.1.2
mc_version_number=260102
java_version=25

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=101
resource_pack_format=84

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_version=0.155.3+26.1.2

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=26.1.154
modmenu_version=18.0.0-beta.1
polymer_version=0.16.5+26.1.2
