# Environment Requirements
minecraft_version=26.1-rc-3
mc_version_number=260100
java_version=25

# Pack Formats TODO
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=94
resource_pack_format=75

# Fabric Properties TODO
# check these on https://fabricmc.net/develop
fabric_version=0.144.0+26.1

# Other Dependencies TODO
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=21.11.153
modmenu_version=17.0.0-beta.2
