# Environment Requirements
minecraft_version=26.1-rc-3
mc_version_number=260100
java_version=25

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=101
resource_pack_format=84

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_version=0.145.1+26.1

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=26.1.154
modmenu_version=18.0.0-alpha.8
