# Environment Requirements
minecraft_version=26.2
mc_version_number=260200
java_version=25

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=107
resource_pack_format=88

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_version=0.160.0+26.2

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=26.1.154
modmenu_version=20.0.0-beta.2
