# Environment Requirements
minecraft_version=26.3
mc_version_number=260300
java_version=25

# Pack Formats
# check these on https://minecraft.wiki/w/Pack_format
data_pack_format=121
resource_pack_format=97

# Fabric Properties
# check these on https://fabricmc.net/develop
fabric_version=0.161.0+26.3

# Other Dependencies
# check these on https://linkie.shedaniel.dev/dependencies
config2_version=26.3.159
modmenu_version=21.0.0-beta.1
polymer_version=0.18.2+26.3
