#if POLYMER
package io.github.mikip98.humilityafm.mod_support.polymer;

import eu.pb4.polymer.blocks.api.BlockModelType;

// TODO: Finish this mapping
public class PolymerNullableBlockModelTypes {
    public static final BlockModelType
            FULL_BLOCK = null,
            LEAVES = #if MC_VERSION < 260000 BlockModelType.TRANSPARENT_BLOCK #else BlockModelType.LEAVES #endif,
//            LEAVES_WATERLOGGED = null,
            BIOME_COLORED_LEAVES = null,
//            BIOME_COLORED_LEAVES_WATERLOGGED = null,
//            FARMLAND = null,
            VINES = #if MC_VERSION < 260000 BlockModelType.VINES_BLOCK #else BlockModelType.VINES #endif,
            PLANT = null,
            BIOME_PLANT = null,
            PROPAGULE = null,
//            PROPAGULE_WATERLOGGED = null,
            KELP = null,
            CACTUS = null,
            TRIPWIRE = null,
            TRIPWIRE_FLAT = null,
            PRESSURE_PLATE_ACTIVE = null,
            HEAD = null,
            // Sculk
            SCULK_SENSOR = null,
//            SCULK_SENSOR_WATERLOGGED = null,
            SCULK_SENSOR_ACTIVE = null,
//            SCULK_SENSOR_ACTIVE_WATERLOGGED = null,
            // Slab
            SLAB_TOP = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.TOP_SLAB #else BlockModelType.SLAB_TOP #endif,
//            SLAB_TOP_WATERLOGGED = null,
            SLAB_BOTTOM = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.BOTTOM_SLAB #else BlockModelType.SLAB_BOTTOM #endif,
//            SLAB_BOTTOM_WATERLOGGED = null,
            // Campfire
            CAMPFIRE = null,
//            CAMPFIRE_WATERLOGGED = null,
            // Trapdoor
            TRAPDOOR_TOP = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.TOP_TRAPDOOR #else BlockModelType.TRAPDOOR_TOP #endif,
            TRAPDOOR_BOTTOM = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.BOTTOM_TRAPDOOR #else BlockModelType.TRAPDOOR_BOTTOM #endif,
            TRAPDOOR_NORTH = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.NORTH_TRAPDOOR #else BlockModelType.TRAPDOOR_NORTH #endif,
            TRAPDOOR_EAST = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.EAST_TRAPDOOR #else BlockModelType.TRAPDOOR_EAST #endif,
            TRAPDOOR_SOUTH = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.SOUTH_TRAPDOOR #else BlockModelType.TRAPDOOR_SOUTH #endif,
            TRAPDOOR_WEST = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.WEST_TRAPDOOR #else BlockModelType.TRAPDOOR_WEST #endif,
//            TRAPDOOR_TOP_WATERLOGGED = null,
//            TRAPDOOR_BOTTOM_WATERLOGGED = null,
//            TRAPDOOR_NORTH_WATERLOGGED = null,
//            TRAPDOOR_EAST_WATERLOGGED = null,
//            TRAPDOOR_SOUTH_WATERLOGGED = null,
//            TRAPDOOR_WEST_WATERLOGGED = null,
            // Lightning rod
            LIGHTNING_ROD_X = null,
            LIGHTNING_ROD_Y = null,
            LIGHTNING_ROD_Z = null,
//            LIGHTNING_ROD_X_WATERLOGGED = null,
//            LIGHTNING_ROD_Y_WATERLOGGED = null,
//            LIGHTNING_ROD_Z_WATERLOGGED = null,
            // Chain
            CHAIN_X = null,
            CHAIN_Y = null,
            CHAIN_Z = null,
//            CHAIN_X_WATERLOGGED = null,
//            CHAIN_Y_WATERLOGGED = null,
//            CHAIN_Z_WATERLOGGED = null,
            // Lantern
            LANTERN = null,
            LANTERN_HANGING = null,
//            LANTERN_WATERLOGGED = null,
//            LANTERN_HANGING_WATERLOGGED = null,
            // Door
            DOOR_NORTH = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.NORTH_DOOR #else BlockModelType.DOOR_NORTH #endif,
            DOOR_EAST = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.EAST_DOOR #else BlockModelType.DOOR_EAST #endif,
            DOOR_SOUTH = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.SOUTH_DOOR #else BlockModelType.DOOR_SOUTH #endif,
            DOOR_WEST = #if MC_VERSION < 12100 null #elif MC_VERSION < 260000 BlockModelType.WEST_DOOR #else BlockModelType.DOOR_WEST #endif,
            // Shelf
            SHELF_NORTH = null,
            SHELF_EAST = null,
            SHELF_SOUTH = null,
            SHELF_WEST = null,
//            SHELF_NORTH_WATERLOGGED = null,
//            SHELF_EAST_WATERLOGGED = null,
//            SHELF_SOUTH_WATERLOGGED = null,
//            SHELF_WEST_WATERLOGGED = null,
            // Scaffolding
            SCAFFOLDING_TOP = null,
//            SCAFFOLDING_TOP_WATERLOGGED = null,
            SCAFFOLDING_BOTTOM = null,
//            SCAFFOLDING_BOTTOM_WATERLOGGED = null,
            // Gate
            GATE_NORTH_SOUTH_INWALL = null,
            GATE_NORTH_SOUTH_INWALL_OPEN = null,
            GATE_NORTH_SOUTH = null,
            GATE_NORTH_SOUTH_OPEN = null,
            GATE_EAST_WEST_INWALL = null,
            GATE_EAST_WEST_INWALL_OPEN = null,
            GATE_EAST_WEST = null,
            GATE_EAST_WEST_OPEN = null,
            // Bed
            BED_NORTH_HEAD = null,
            BED_NORTH_FOOT = null,
            BED_EAST_HEAD = null,
            BED_EAST_FOOT = null,
            BED_SOUTH_HEAD = null,
            BED_SOUTH_FOOT = null,
            BED_WEST_HEAD = null,
            BED_WEST_FOOT = null,
            // Bars
            BARS_CENTER = null,
//            BARS_CENTER_WATERLOGGED = null,
            BARS_NORTH = null,
//            BARS_NORTH_WATERLOGGED = null,
            BARS_SOUTH = null,
//            BARS_SOUTH_WATERLOGGED = null,
            BARS_NORTH_SOUTH = null,
//            BARS_NORTH_SOUTH_WATERLOGGED = null,
            BARS_WEST = null,
//            BARS_WEST_WATERLOGGED = null,
            BARS_NORTH_WEST = null,
//            BARS_NORTH_WEST_WATERLOGGED = null,
            BARS_SOUTH_WEST = null,
//            BARS_SOUTH_WEST_WATERLOGGED = null,
            BARS_NORTH_SOUTH_WEST = null,
//            BARS_NORTH_SOUTH_WEST_WATERLOGGED = null,
            BARS_EAST = null,
//            BARS_EAST_WATERLOGGED = null,
            BARS_NORTH_EAST = null,
//            BARS_NORTH_EAST_WATERLOGGED = null,
            BARS_EAST_SOUTH = null,
//            BARS_EAST_SOUTH_WATERLOGGED = null,
            BARS_NORTH_EAST_SOUTH = null,
//            BARS_NORTH_EAST_SOUTH_WATERLOGGED = null,
            BARS_EAST_WEST = null,
//            BARS_EAST_WEST_WATERLOGGED = null,
            BARS_NORTH_EAST_WEST = null,
//            BARS_NORTH_EAST_WEST_WATERLOGGED = null,
            BARS_EAST_SOUTH_WEST = null,
//            BARS_EAST_SOUTH_WEST_WATERLOGGED = null,
            BARS_NORTH_EAST_SOUTH_WEST = null;
//            BARS_NORTH_EAST_SOUTH_WEST_WATERLOGGED = null;
//            // Fire
//            FIRE = null,
//            FIRE_UP = null,
//            FIRE_NORTH = null,
//            FIRE_NORTH_UP = null,
//            FIRE_SOUTH = null,
//            FIRE_SOUTH_UP = null,
//            FIRE_NORTH_SOUTH = null,
//            FIRE_NORTH_SOUTH_UP = null,
//            FIRE_WEST = null,
//            FIRE_WEST_UP = null,
//            FIRE_NORTH_WEST = null,
//            FIRE_NORTH_WEST_UP = null,
//            FIRE_SOUTH_WEST = null,
//            FIRE_SOUTH_WEST_UP = null,
//            FIRE_NORTH_SOUTH_WEST = null,
//            FIRE_NORTH_SOUTH_WEST_UP = null,
//            FIRE_EAST = null,
//            FIRE_EAST_UP = null,
//            FIRE_NORTH_EAST = null,
//            FIRE_NORTH_EAST_UP = null,
//            FIRE_EAST_SOUTH = null,
//            FIRE_EAST_SOUTH_UP = null,
//            FIRE_NORTH_EAST_SOUTH = null,
//            FIRE_NORTH_EAST_SOUTH_UP = null,
//            FIRE_EAST_WEST = null,
//            FIRE_EAST_WEST_UP = null,
//            FIRE_NORTH_EAST_WEST = null,
//            FIRE_NORTH_EAST_WEST_UP = null,
//            FIRE_EAST_SOUTH_WEST = null,
//            FIRE_EAST_SOUTH_WEST_UP = null,
//            FIRE_NORTH_EAST_SOUTH_WEST = null;
//            // Stairs
//            STAIRS_NORTH_TOP_STRAIGHT = null,
//            STAIRS_NORTH_TOP_STRAIGHT_WATERLOGGED = null,
//            STAIRS_NORTH_TOP_INNER_LEFT = null,
//            STAIRS_NORTH_TOP_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_NORTH_TOP_INNER_RIGHT = null,
//            STAIRS_NORTH_TOP_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_NORTH_TOP_OUTER_LEFT = null,
//            STAIRS_NORTH_TOP_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_NORTH_TOP_OUTER_RIGHT = null,
//            STAIRS_NORTH_TOP_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_NORTH_BOTTOM_STRAIGHT = null,
//            STAIRS_NORTH_BOTTOM_STRAIGHT_WATERLOGGED = null,
//            STAIRS_NORTH_BOTTOM_INNER_LEFT = null,
//            STAIRS_NORTH_BOTTOM_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_NORTH_BOTTOM_INNER_RIGHT = null,
//            STAIRS_NORTH_BOTTOM_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_NORTH_BOTTOM_OUTER_LEFT = null,
//            STAIRS_NORTH_BOTTOM_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_NORTH_BOTTOM_OUTER_RIGHT = null,
//            STAIRS_NORTH_BOTTOM_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_EAST_TOP_STRAIGHT = null,
//            STAIRS_EAST_TOP_STRAIGHT_WATERLOGGED = null,
//            STAIRS_EAST_TOP_INNER_LEFT = null,
//            STAIRS_EAST_TOP_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_EAST_TOP_INNER_RIGHT = null,
//            STAIRS_EAST_TOP_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_EAST_TOP_OUTER_LEFT = null,
//            STAIRS_EAST_TOP_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_EAST_TOP_OUTER_RIGHT = null,
//            STAIRS_EAST_TOP_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_EAST_BOTTOM_STRAIGHT = null,
//            STAIRS_EAST_BOTTOM_STRAIGHT_WATERLOGGED = null,
//            STAIRS_EAST_BOTTOM_INNER_LEFT = null,
//            STAIRS_EAST_BOTTOM_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_EAST_BOTTOM_INNER_RIGHT = null,
//            STAIRS_EAST_BOTTOM_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_EAST_BOTTOM_OUTER_LEFT = null,
//            STAIRS_EAST_BOTTOM_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_EAST_BOTTOM_OUTER_RIGHT = null,
//            STAIRS_EAST_BOTTOM_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_TOP_STRAIGHT = null,
//            STAIRS_SOUTH_TOP_STRAIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_TOP_INNER_LEFT = null,
//            STAIRS_SOUTH_TOP_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_SOUTH_TOP_INNER_RIGHT = null,
//            STAIRS_SOUTH_TOP_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_TOP_OUTER_LEFT = null,
//            STAIRS_SOUTH_TOP_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_SOUTH_TOP_OUTER_RIGHT = null,
//            STAIRS_SOUTH_TOP_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_BOTTOM_STRAIGHT = null,
//            STAIRS_SOUTH_BOTTOM_STRAIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_BOTTOM_INNER_LEFT = null,
//            STAIRS_SOUTH_BOTTOM_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_SOUTH_BOTTOM_INNER_RIGHT = null,
//            STAIRS_SOUTH_BOTTOM_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_SOUTH_BOTTOM_OUTER_LEFT = null,
//            STAIRS_SOUTH_BOTTOM_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_SOUTH_BOTTOM_OUTER_RIGHT = null,
//            STAIRS_SOUTH_BOTTOM_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_WEST_TOP_STRAIGHT = null,
//            STAIRS_WEST_TOP_STRAIGHT_WATERLOGGED = null,
//            STAIRS_WEST_TOP_INNER_LEFT = null,
//            STAIRS_WEST_TOP_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_WEST_TOP_INNER_RIGHT = null,
//            STAIRS_WEST_TOP_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_WEST_TOP_OUTER_LEFT = null,
//            STAIRS_WEST_TOP_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_WEST_TOP_OUTER_RIGHT = null,
//            STAIRS_WEST_TOP_OUTER_RIGHT_WATERLOGGED = null,
//            STAIRS_WEST_BOTTOM_STRAIGHT = null,
//            STAIRS_WEST_BOTTOM_STRAIGHT_WATERLOGGED = null,
//            STAIRS_WEST_BOTTOM_INNER_LEFT = null,
//            STAIRS_WEST_BOTTOM_INNER_LEFT_WATERLOGGED = null,
//            STAIRS_WEST_BOTTOM_INNER_RIGHT = null,
//            STAIRS_WEST_BOTTOM_INNER_RIGHT_WATERLOGGED = null,
//            STAIRS_WEST_BOTTOM_OUTER_LEFT = null,
//            STAIRS_WEST_BOTTOM_OUTER_LEFT_WATERLOGGED = null,
//            STAIRS_WEST_BOTTOM_OUTER_RIGHT = null,
//            STAIRS_WEST_BOTTOM_OUTER_RIGHT_WATERLOGGED = null;
}
#endif